version: '3.11'

services:
  fastapi-app:
    build: .
    depends_on:
      - mongodb  # Ensures FastAPI waits for MongoDB to be ready
    environment:
      - MONGO_URI=mongodb://mongodb:27017  # Correct URI for FastAPI to use
    ports:
      - "8000:8000"  # Maps port 5000 on the host to port 5000 in the container
    networks:
      - app-network

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      retries: 5
      timeout: 5s
      start_period: 5s
    networks:
      - app-network
  

networks:
  app-network:
    driver: bridge


volumes:
  mongodb_data:
